version: '3.8'

services:
  database_congelatech:
    image: postgres
    container_name: database_congelatech
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=congelatech
      - POSTGRES_PASSWORD=congela
      - POSTGRES_DB=congelatech
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: congelatech
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata: 
    driver: local